baseURL: "https://wyattpfeil.com/"
languageCode: "en-us"
title: "Wyatt Pfeil"
theme: "casper3"

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - Name: "Home"
      URL: "/"
      weight: 10
    - Name: "About"
      URL: "/about/"
      weight: 20
    - Name: "iOS Apps"
      URL: "/ios-apps/"
      weight: 30
    - Name: "Contact"
      URL: "/contact/"
      weight: 40

author:
  name: "Wyatt Pfeil"
  website: "https://wyattpfeil.com"
